module.exports = {
  SP_INSERT_BONIFICACION: "CALL SP_INSERT_BONIFICACION(?,?,?,?)",
  SP_UPDATE_BONIFICACION: "CALL SP_UPDATE_BONIFICACION(?,?,?,?,?,?)",
  SP_SEARCH_BONIFICACIONES: "CALL SP_SEARCH_BONIFICACIONES(?,?)",
  GET_BONIFICACIONES: "SELECT * FROM bonificacion_servicios",
  GET_BONIFICACION: "SELECT * FROM bonificacion_servicios WHERE id = ?",
};
