module.exports = {
  SP_INSERT_NOVEDAD: "CALL SP_INSERT_NOVEDAD(?,?,?,?,?,?)",
  SP_UPDATE_NOVEDAD: "CALL SP_UPDATE_NOVEDAD(?,?,?,?,?,?,?,?)",
  SP_SEARCH_NOVEDADES: "CALL SP_SEARCH_NOVEDADES(?,?,?,?,?)",
  GET_NOVEDADES: "SELECT * FROM novedades",
  GET_NOVEDAD: "SELECT * FROM novedades WHERE id=?",
};
