module.exports = {
  SP_INSERT_LIQUIDACION: "CALL SP_INSERT_LIQUIDACION(?,?,?)",
  SP_UPDATE_LIQUIDACION: "CALL SP_UPDATE_LIQUIDACION(?,?,?,?,?)",
  SP_SEARCH_LIQUIDACION: "CALL SP_SEARCH_LIQUIDACION(?,?,?)",
  GET_LIQUIDACIONES: "SELECT * FROM liquidaciones",
  GET_LIQUIDACION: "SELECT * FROM liquidaciones WHERE id = ?",
};
